### ISSUE TITLE
memcached backend for the cache

### ISSUE THREAD

**Issue by vavrusa** [CZ-NIC/knot-resolver#1]
### Problem

The resolver now has LMDB backend (and in-memory trie in theory). This is good enough for most deployments and has local replication. Some anycasts might want to do distributed cache and remote replication.

### Outcome

* [ ] Document namedb API (libknot)
* [ ] Implement memcached backend for namedb API

**Comment by leousr123** [comment]
> do you want to provide a different cache backend, or add another cache after the local cache
>
Not sure if I fully understand the question, I probably the answer is no, I don't want cold cache, but want (same as OpenDNS, 8.8.8.8, 8.34.34.34, etc.) that when a user queries an Asian node for bla.tld that a user who then hits a European node would receive a reply from the then synchronised cache.
That is, except when "edns-client-subnet" is used for efficient use of CDN's (publised at http://www.afasterinternet.com/ietfdraft.htm )

I thought about Memcached since it's widely used and documented, and could listen both on socket (faster and less overhead) and on IP. Since memcached is key/value only, I don't know if it's suitable enough, but I'm unaware of LMDB being able to replicate "streaming".

**Comment by vavrusa** [comment]
The question was - is memcached quick enough or do we need a local cache in addition to it.
Either way, I've glimpsed through the API and it's very suitable just like redis or anything else out there. I'll give it a shot and we'll see.

LMDB on itself can't replicate changes, but the resolver can monitor transaction commits to the cache and broadcast them, but this is more difficult than simply relying on distributed k-v storage to do it for us.

**Comment by vavrusa** [comment]
Merged in f01587a
