### ISSUE TITLE
How to install multiserver

### ISSUE THREAD

**Issue by ThuanDoHung** [CZ-NIC/knot-resolver#101]
Hi,
I want deploy multiserver for knot resolver (ex: for HA, loadblancer, Backup DC,..). I try use Nginx Stream for forward request query for Knot Resolver but i can not receive client ip request from dnstap of Knot Resolver (all ip is of Nginx).
How can i deploy multi Knot Resolver?

**Comment by Spiffyk** [comment]
Hi, if I understand you properly, you have an Nginx HTTPS reverse proxy, through which you are sending DNS-over-HTTPS queries to Knot Resolver, correct? And what you want is to receive the addresses of the actual clients instead of the proxy in Knot Resolver, correct?

If so, then you may be able to use the [PROXY protocol, which Knot Resolver supports](https://knot-resolver.readthedocs.io/en/stable/daemon-bindings-net_server.html#proxyv2-protocol). I have not tested this, but [Nginx seems to support this in its `ngx_stream_proxy_module`](https://nginx.org/en/docs/stream/ngx_stream_proxy_module.html#proxy_protocol). In case Nginx does not work out and you are able to use something else that *does* support PROXYv2, it should not be a problem. [dnsdist](https://dnsdist.org/) is one such proxy, specifically designed for DNS, that supports PROXYv2 - in fact, it's what we use in our automated tests to check that PROXYv2 works.

**Comment by ThuanDoHung** [comment]
> Hi, if I understand you properly, you have an Nginx HTTPS reverse proxy, through which you are sending DNS-over-HTTPS queries to Knot Resolver, correct? And what you want is to receive the addresses of the actual clients instead of the proxy in Knot Resolver, correct?
> 
> If so, then you may be able to use the [PROXY protocol, which Knot Resolver supports](https://knot-resolver.readthedocs.io/en/stable/daemon-bindings-net_server.html#proxyv2-protocol). I have not tested this, but [Nginx seems to support this in its `ngx_stream_proxy_module`](https://nginx.org/en/docs/stream/ngx_stream_proxy_module.html#proxy_protocol). In case Nginx does not work out and you are able to use something else that _does_ support PROXYv2, it should not be a problem. [dnsdist](https://dnsdist.org/) is one such proxy, specifically designed for DNS, that supports PROXYv2 - in fact, it's what we use in our automated tests to check that PROXYv2 works.

Thanks so much @Spiffyk
