### ISSUE TITLE
Building from source doesn't get library link correct

### ISSUE THREAD

**Issue by paulehoffman** [CZ-NIC/knot-resolver#30]
Greetings. In /root/Source/knot-resolver, I give the command:
   make install PREFIX=/root/Target/knot-resolver
/root/Target/knot-resolver/sbin/kresd is built. /root/Target/knot-resolver/lib shows:
drwxr-xr-x 4 root root 4.0K Jul 29 11:20 kdns_modules
lrwxrwxrwx 1 root root   12 Jul 29 11:20 libkres.so -> libkres.so.1
-rwxr-xr-x 1 root root 214K Jul 29 11:20 libkres.so.1
drwxr-xr-x 2 root root 4.0K Jul 29 11:20 pkgconfig
However, /root/Target/knot-resolver/sbin/kresd -h returns:
   /root/Target/knot-resolver/sbin/kresd: error while loading shared libraries: libkres.so.1: cannot open shared object file: No such file or directory

Clues? Fixes?

**Comment by vavrusa** [comment]
Hi, you're building with a shared library and installing to custom location.
You can either build it statically (see manual) or add the library to the linker path, otherwise linker can't find the library (see http://tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html)
It's similar problem to installing a binary outside of `$PATH` and expecting shell to find it somehow.

If you want to use shared library, you can either tell linker to add extra search path through env:

```bash
$ make install PREFIX=/root/Target/knot-resolver
# Let linker know about your path through env
$ LD_LIBRARY_PATH=/root/Target/knot-resolver/lib /root/Target/knot-resolver/sbin/kresd
```

Add it to linker search path:

```bash
$ make install PREFIX=/root/Target/knot-resolver
# Add the installation path to linker paths
$ echo "/root/Target/knot-resolver/lib" | sudo tee /etc/ld.so.conf.d/knot-resolver.conf
$ sudo ldconfig
$ /root/Target/knot-resolver/sbin/kresd
```

or install to prefix that the linker already knows about (e.g. `/usr/local`)

**Comment by paulehoffman** [comment]
Thanks. That wasn't clear from the documentation. Maybe "Static or Dynamic?" section should be right after the "Building from Sources" section? 'make install PREFIX="/usr/local"' feels like it should make a usable program; possibly that recipe should include the BUILDMODE=static to make it work as expected.

**Comment by vavrusa** [comment]
I'll include a note in the documentation, dynamic linking is a pitfall, thanks for pointing it out.
`make install PREFIX="/usr/local"` should make a usable program since `/usr/local/lib` is going to be in linker search path most likely.
