### ISSUE TITLE
Feature request: try upstream servers in sequence / as fallback

### ISSUE THREAD

**Issue by Jamesits** [CZ-NIC/knot-resolver#49]
Currently `policy.STUB` and `policy.FORWARD` selects the fastest server in server list. Can there be an option to let it try in config sequence? (It is better if timeout can be set in config)

I wish there is some mechanism if a policy (even non-chained one) fails, the request can continue to the next policy. But this seems to be much difficult to implement.

==========
Origin issue:

Is servers specified in FORWARD policy tried randomly or in sequence?

I want to set some servers only for backup (since they are not replying very good results). Is this possible with FORWARD policy?

**Comment by vcunat** [comment]
Older kresd versions tried them in order.  Since 1.3.2 it tracks the response times and prefers those that answer faster.

**Comment by Jamesits** [comment]
@vcunat So is there any ways to let it try in order in the edge version? In my case the server with lowest response time is not the best server I want to use. Or is there some way I can let it try another set of servers when one set of servers fail to respond?

**Comment by vcunat** [comment]
kresd will retry with a different server if one fails to respond; that hasn't changed.

**Comment by Jamesits** [comment]
@vcunat 

I live in China, as you may know, some DNS requests are modified when they go through [GFW](https://en.wikipedia.org/wiki/Great_Firewall). In order to get correct results, I want to let knot-resolver try to resolve everything through a VPN tunneled DNS server first, and if it fails (the tunnel may be down) then try again with my ISP's DNS. However the tunneled DNS server always responds slower than ISP's dns server since the tunnel has overhead and increases the latency. Is this possible?

**Comment by vcunat** [comment]
Hmm, I suspect this will be a complicated situation &ndash; if kresd gets a reasonably looking reply (matching port, query ID, etc.) that fails DNSSEC validation, it will return SERVFAIL to the client and only retry if asked again by the client.  That might be happening when you fall back to queries that get modified (by GFW); I don't really know if *you* prefer at least modified answer instead of SERVFAIL :-)  *I consider myself lucky not to have to worry much about such issues.*

I suppose it might even make sense to add a specific mode to kresd for similar use cases, if there are multiple aspects that are better changed, but I'm not really familiar with what exactly GFW does to DNS traffic.  Even with DNSSEC it's all optimized for the "usual" case where no manipulation is attempted.

Can you try if the sequential approach in 1.3.0 or 1.3.1 works OK in that case?  We could re-add that as an option.  Note that all the servers have to be in a single `FORWARD` directive, as in [an example in docs](https://knot-resolver.readthedocs.io/en/latest/modules.html#id2).  The default retransmit-timeout is 250ms, so in the sequential approach the second server "wins" a query if it answers faster than the first by more than 250ms.

**Comment by oerdnj** [comment]
@Jamesits The other option would be to look at the policy.lua and you might try writing a snippet of lua code that would do exactly what you want to do - e.g. chaining two FORWARDs together. 

Or if you know the set of domains you want to to resolve through VPN, you can specify some combination of policies (instead of using `policy.all()`).

**Comment by pspacek** [comment]
If you prefer "some" answer no matter how modified it is just disable DNSSEC validation.

In my opinion this use-case would be better solved by some configuration management tool. If tunnel is up, generate config pointing to the VPN DNS resolver. If it is down, generate config pointing to ISP DNS server.

**Comment by vcunat** [comment]
It's a bit inconvenient that FORWARD needs even more round trips than plain iteration, because some DNSSEC-related records are harder to get from non-authoritative servers than authoritative ones.  The unverified STUB mode through a trusted VPN might be a more usable option in your high-latency case, due to simply passing queries through, 1-1 with added caching.

**Comment by Jamesits** [comment]
@vcunat The try-in-sequence behavior should solve my question. It would be better if there are some more options (e.g. If a FORWARD directive fails to get a valid answer, then the request is chained to other policies, or maybe some option to customize the timeout).

BTW, about the GFW manuipulation: if the reply packet contains blocked domains, the ISP gateway sends a fake packet with a random IPv4 result before the correct packet arrives. If the request uses TCP, it is simply discarded.
![image](https://user-images.githubusercontent.com/1297257/29267470-73f667bc-811b-11e7-9a02-7a6143da6718.png)

**Comment by Jamesits** [comment]
@pspacek What I'm trying to achieve is: if the VPN is up, tunnel all DNS requests through VPN; if the VPN is down, requests go to my local ISP's DNS but if DNSSEC validation fails, just generate SERVFAIL. The VPN runs on my router so it is not very convenient to get up and down status on DNS server.

**Comment by vcunat** [comment]
With current kresd, you can only patch the timeout before compilation, but it's a trivial change (KR_CONN_RETRY).  You could also e.g. put the first IP twice into the FORWARD directive, so the third option is only tried after 500ms.

Once you have the IP, is it relatively safe already?  I would expect at least some IP-level blocking as well, forcing you to VPN tunneling for much more than just DNS.

**Comment by Jamesits** [comment]
@oerdnj Thanks for your advice. I've been looking into the source code; but as a programmer I prefer some generic solution rather than patching a function for a special case. As far as I know, `policy.lua` only calls `set_nslist` and cannot get the resolution result. I wonder if there is some way to implement chained FORWARD/STUB (i.e. if one policy fail, it will continue on the policy list until resolved successfully or reached end).

@vcunat I have convenient ways to deal with IP blocking: just set up a split tunnel and throw all the blocked data in. However DNS spoofing is a lot more complex. The spoofing happens in every ISP's border gateway, which means every DNS server in my country, if not set up against spoofing, has a bunch of polluted entries in their caches. If I just put recursive resolver to these servers, even if I have VPN set up, the blocked websites are still blocked. Sometimes [fake DNS results are not just random](https://techcrunch.com/2007/10/18/baidu-hijacking-google-traffic-in-china/), or even used to [attack sites](http://www.ibtimes.com/chinas-great-cannon-lets-internet-censors-hack-sites-abroad-just-ask-github-1877180). In China there are 4 major ISPs who [charge each other a lot for interconnecting](http://www.sohu.com/a/109949125_116039) (I can't find an English report about that) so Chinese multimedia sites relies a lot on GeoDNS to select the correct server based on ISP. I still need local ISP's DNS server to resolve media sites and CDNs. I'm new to knot resolver so I guess I'll first set up some fallback strategy then consider spliting domestic websites to local ISP DNS servers.

**Comment by vcunat** [comment]
I don't see an easy way to achieve the sequential attempts by adding/changing lua code.  @Jamesits: before 1.3.2 you only have sequential attempts for forwarding and stub modes; since 1.3.2 you can locally apply a trivial patch to achieve that, e.g.:
```diff
diff --git a/lib/resolve.c b/lib/resolve.c
index fabcdd00..544f9b0a 100644
--- a/lib/resolve.c
+++ b/lib/resolve.c
@@ -1389,7 +1389,7 @@ ns_election:
        if (qflg.AWAIT_IPV4 || qflg.AWAIT_IPV6) {
                kr_nsrep_elect_addr(qry, request->ctx);
        } else if (qflg.FORWARD || qflg.STUB) {
-               kr_nsrep_sort(&qry->ns, request->ctx->cache_rtt);
+               //kr_nsrep_sort(&qry->ns, request->ctx->cache_rtt);
        } else if (!qry->ns.name || !retry) { /* Keep NS when requerying/stub/badcookie. */
                /* Root DNSKEY must be fetched from the hints to avoid chicken and egg problem. */
                if (qry->sname[0] == '\0' && qry->stype == KNOT_RRTYPE_DNSKEY) {
```

**Comment by pspacek** [comment]
@Jamesits It should be possible to use `policy.suffix` for TLD `cn` to direct all `cn.` traffic to ISPs servers and use `policy.all` for the rest. The first match wins so order `suffix, all` might be the optimization you want.

**Comment by Jamesits** [comment]
@pspacek I already have a similar setup. But most sites in China use `.com` TLD (there are special regulations on `.cn` about 10 years ago so many people started with `.com`... I can't remember that clear). Thanks anyway.

**Comment by Jamesits** [comment]
I guess this issue can be a feature request ;)

**Comment by pspacek** [comment]
Given how specific this use-case is, it should definitelly go to a separate module or something similarly isolated. If write some code which meets your requirements please send it for review using our Gitlab: https://gitlab.labs.nic.cz/knot/knot-resolver/

I'm going to close this issue here because we are migrating everything to Gitlab. Thank you for understanding.
